# Generated by Django 3.1.5 on 2021-03-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notelog', '0002_auto_20210318_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
